version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  mongo:
    image: mongo:4
    container_name: todo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
